package domain;

import javax.swing.filechooser.FileSystemView;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.*;

public class Configuration {
	private static final String DEFAULT_FILENAME_LEGACY = "config.txt";
	private static final String DEFAULT_FILENAME_CURRENT = ".mudiiclient.config.xml";

	public static final String KEY_COMMAND_REMAINS = "command.remains";
	public static final String KEY_ENTER_RESENDS = "enter.resends";
	public static final String KEY_LOGGING = "logging";
	public static final String KEY_ACTIVE_DATA_COLLECTION = "active.data.collection";
	public static final String KEY_MAX_WIDTH_80 = "max.width.80";
	public static final String KEY_INVERT_MOUSE_WHEEL_SCROLLING = "mouse.wheel.inverted";
	public static final String KEY_AUTO_PLAY = "auto.play";
	public static final String KEY_LOG_DIRECTORY = "log.directory";

	public static final int DEFAULT_ENTER_RESENDS = 1;
	public static final int DEFAULT_COMMAND_REMAINS = 0;
	public static final int DEFAULT_LOGGING = 1;
	public static final int DEFAULT_ACTIVE_DATA_COLLECTION = 1;
	public static final int DEFAULT_MAX_WIDTH_80 = 0;
	public static final int DEFAULT_INVERT_MOUSE_WHEEL_SCROLLING = 0;
	public static final int DEFAULT_AUTO_PLAY = 1;

	Properties properties;
	
	public String getSetting(String key, String defaultValue) {
		checkProperties();
		
		String value = (String) properties.get(key);
		if (value == null) {
			value = defaultValue;
			if (defaultValue != null) {
				setSetting(key, defaultValue);
			}
		}
		
		return value;
	}

	private void checkProperties() {
		if (properties == null) {
			properties = new Properties() {
				public Set entrySet() {
					ArrayList sorted = new ArrayList(super.entrySet());
					Collections.sort(sorted, new Comparator() {
						public int compare(Object o1, Object o2) {
							String key1 = (String) ((Map.Entry) o1).getKey();
							String key2 = (String) ((Map.Entry) o2).getKey();
							return key1.compareTo(key2);
						}
					});
					return Collections.unmodifiableSet(new LinkedHashSet(sorted));
				}
			};
			try {
				properties.loadFromXML(new FileInputStream(getFile()));
			} catch (IOException e) {
				// TODO Auto-generated catch block
//				e.printStackTrace();
			}
		}
	}
	
	public String getSetting(String key) {
		return getSetting(key, null);
	}
	
	public void setSetting(String key, Object value) {
		checkProperties();
		
		if (value == null) {
			properties.setProperty(key, null);
		} else {
			properties.setProperty(key, value.toString());
		}
		
		try {
			properties.storeToXML(new FileOutputStream(getFile()), "Do not edit this file! Especially not while the app is running. I warned you..");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private File getFile() {
		File homeDir = FileSystemView.getFileSystemView().getDefaultDirectory();

		String documentsPath = homeDir.toString() + File.separator + "Documents";
		File documentsDir = new File(documentsPath);
		File documentsFile = new File(documentsPath, DEFAULT_FILENAME_CURRENT);

		String myDocumentsPath = homeDir.toString() + File.separator + "My Documents";
		File myDocumentsDir = new File(myDocumentsPath);
		File myDocumentsFile = new File(myDocumentsPath, DEFAULT_FILENAME_CURRENT);

		File homeFile = new File(homeDir.toString(), DEFAULT_FILENAME_CURRENT);

		File legacyFile = new File(DEFAULT_FILENAME_LEGACY);

		if (documentsFile.exists()) {
			return documentsFile;
		} else if (myDocumentsFile.exists()) {
			return myDocumentsFile;
		} else if (homeFile.exists()) {
			return homeFile;
		} else if (legacyFile.exists()) {
			return legacyFile;
		}

		if (documentsDir.isDirectory() && documentsDir.canWrite()) {
			return documentsFile;
		} else if (myDocumentsDir.isDirectory() && myDocumentsDir.canWrite()) {
			return myDocumentsFile;
		} else if (homeDir.isDirectory() && homeDir.canWrite()) {
			return homeFile;
		} else {
			return legacyFile;
		}
	}

	public String getDefaultLogDirectory() {
		String parent = getFile().getParent();
		String parentPath = parent == null || parent.isEmpty() ? "" : parent + File.separator;
		return parentPath + "Mud2Logs";
	}

	public int getInt(String key, int defaultValue) {
		int value = defaultValue;
		try {
			value = Integer.parseInt(getSetting(key));
		} catch (Exception e) {
			
		}
		return value;
	}

	public void setInt(String key, int value) {
		setSetting(key, Integer.toString(value));
	}

	public Properties getSettings() {
		checkProperties();

		return properties;
	}
}
